version: '3.8'

services:
  db:
    image: postgres:17
    container_name: cocos-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocos
    ports:
      - '5432:5432'
    command: >
      postgres
      -c shared_buffers=256MB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  test_db:
    image: postgres:17
    container_name: cocos-postgres-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cocos_test
    ports:
      - '5433:5432'
    volumes:
      - ./init.test.sql:/docker-entrypoint-initdb.d/init.test.sql